[feedhandler]
feed_uri = "wss://ws-feed.exchange.coinbase.com"
ticker = "SOL-USD"
queue_size = 1000
subscription_port = 8001
prom_exporter_port = 9001

[vwap]
feed_uri = "ws://localhost:8001/subscribe"
subscription_port = 8002
bar_queue_len = 1440
prom_exporter_port = 9002